name: cicd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  NODE_ENV: ci
  SERVICE_NAME: ${{ github.event.repository.name }}
  GITHUB_TOKEN: ${{ secrets.JCB_GITHUB_PACKAGE_TOKEN }}

permissions:
  contents: "read"
  id-token: "write"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      AWS_SQS_ENDPOINT: http://localhost:4566
      SQS_QUEUE_BASE_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: sqs
          DEBUG: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install awslocal
        run: pip3 install awscli-local

      - name: Setup LocalStack
        run: ./scripts/localstack.sh

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "^20.9.0"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --frozen-lockfile

      - name: Run build
        run: npm run build:all

      - name: Run Tests
        run: npm run test:all

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "^20.9.0"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --frozen-lockfile

      - name: Run build
        run: npm run eslint:all

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "^20.9.0"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --frozen-lockfile

      - name: Run build
        run: npm run build:all

  publish:
    needs: [build, lint, test]
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "^20.9.0"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --frozen-lockfile

      - name: Run build
        run: npm run build:all

      - name: Run lint
        run: npm run eslint:all

      - name: Publish to NPM
        run: npm run publish:all
