name: cicd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  NODE_ENV: ci
  SERVICE_NAME: ${{ github.event.repository.name }}

permissions:
  contents: "read"
  id-token: "write"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "^20.9.0"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --frozen-lockfile

      - name: Run Tests
        run: npm run test:all

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "^20.9.0"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --frozen-lockfile

      - name: Run build
        run: npm run lint:all

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "^20.9.0"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --frozen-lockfile

      - name: Run build
        run: npm run build:all

  publish:
    needs: [build, lint, test]
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    env:
      GITHUB_TOKEN: ${{ secrets.JCB_GITHUB_PACKAGE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "^20.9.0"
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --frozen-lockfile

      - name: Run test
        run: npm run test:all

      - name: Run build
        run: npm run build:all

      - name: Run lint
        run: npm run lint:all

      - name: Publish to NPM
        run: npm run publish:all
